
services:
  postgresql:
    build:
      context: ./PostgresDB
      dockerfile: Dockerfile
      target: no-crypto-fetch-setup
    container_name: crypto_postgres
    env_file:
      - ./PostgresDB/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  localstack:
    container_name: "crypto_localstack"
    image: localstack/localstack:latest
    env_file:
      - ./localstack/environments/.env.local
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    volumes:
      - localstack_data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  user_service_unit:
    # Build the image from the Dockerfile in the /UserService directory
    build:
      context: ./UserService
      dockerfile: Dockerfile.dev
      target: unit-test #unit-test, integration-test, full-test, production (no tests are run)
    container_name: crypto_user_service
    env_file:
      - ./UserService/.env

    # Host the FastAPI application on port 8000
    ports:
      - "8000:8000"

    depends_on:
      postgresql:
        condition: service_healthy
      kafka:
        condition: service_started
      debezium:
        condition: service_healthy


    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: rebuild
          path: ./UserService
          target: /app
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - .venv/

        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock
  
  subscription_service_unit:
    # Build the image from the Dockerfile in the /UserService directory
    build:
      context: ./SubscriptionService
      dockerfile: Dockerfile.dev
      target: unit-test #unit-test, integration-test, full-test, production (no tests are run)
    container_name: crypto_subscription_service
    env_file:
      - ./SubscriptionService/.env

    # Host the FastAPI application on port 8000
    ports:
      - "8001:8001"

    depends_on:
      postgresql:
        condition: service_healthy
      kafka:
        condition: service_started
      debezium:
        condition: service_healthy


    develop:
      # Create a `watch` configuration to update the app
      # https://docs.docker.com/compose/file-watch/#compose-watch-versus-bind-mounts
      watch:
        # Sync the working directory with the `/app` directory in the container
        - action: rebuild
          path: ./SubscriptionService
          target: /app
          # Exclude the project virtual environment — it could be for a
          # different platform in the container
          ignore:
            - .venv/

        # Rebuild the image if dependencies change by checking uv.lock
        - action: rebuild
          path: ./uv.lock
  
  kafka:
    image: apache/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "${KAFKA_PORT:-9092}:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: ${KAFKA_CLUSTER_ID:-MkU3OEVBNTcwNTJENDM2Qk}
    volumes:
      - ./tmp/kraft-combined-logs:/tmp/kraft-combined-logs

  debezium:
    image: quay.io/debezium/connect:latest
    container_name: debezium
    ports:
      - "${DEBEZIUM_PORT:-8083}:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: debezium_connect_config
      OFFSET_STORAGE_TOPIC: debezium_connect_offsets
      STATUS_STORAGE_TOPIC: debezium_connect_statuses
    depends_on:
      kafka:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/connectors"]
      interval: 10s
      timeout: 30s
      retries: 20
      start_period: 30s

volumes:
  postgres_data:
    driver: local
  localstack_data:
    driver: local